language: cpp

compiler:
  - gcc
  - clang

notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always
        template:
                - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
                - "Change view : %{compare_url}"
                - "Build details: %{build_url}"
                - "Result: %{result}"

cache: apt

before_install:
        # Debugging
        - lsb_release -sc
        # Update repositories to not be shit.
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
        - sudo apt-get clean
        - sudo apt-get update
        # Update dependancies
        #- scripts/deps.sh


install:
        # Install dependencies
        - sudo apt-get install -f -y libtorrent-rasterbar-dev libboost-all-dev 
        # Update g++ to 4.9
        - sudo apt-get install -f -y g++
        - sudo apt-get install -f -y clang
        - wget http://optimate.dl.sourceforge.net/project/libtorrent/libtorrent/libtorrent-rasterbar-1.0.0.tar.gz
        - tar -xzf libtorrent-rasterbar-1.0.0.tar.gz
        - cd libtorrent-rasterbar-1.0.0
        - ./configure --prefix=/usr
        - make
        - sudo make install
        - cd ..
script:
        - mkdir -p build/
        - cd build/
        - cmake ..
        - make -j`nproc`
