language: cpp

compiler:
  - gcc
  - clang

notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always
        template:
                - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
                - "Change view : %{compare_url}"
                - "Build details: %{build_url}"
                - "Result: %{result}"

before_install:
        # Debugging
        - lsb_release -sc
        # Update repositories to not be shit.
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ utopic universe multiverse"
        - sudo apt-get update
        # Update dependancies
        #- scripts/deps.sh

install:
        # Install dependancies
        #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
        - mkdir -p build/
        - cd build/
        - cmake ..
        - make -j`nproc`
